namespace Echokraut.Services.Queue;

/// <summary>
/// Represents the lifecycle state of a voice message
/// </summary>
public enum VoiceMessageState
{
    /// <summary>
    /// Message is queued, waiting for backend to be ready
    /// </summary>
    PendingGeneration,
    
    /// <summary>
    /// Message is being generated by the TTS backend
    /// </summary>
    Generating,
    
    /// <summary>
    /// Message has been generated and is waiting to play
    /// </summary>
    ReadyToPlay,
    
    /// <summary>
    /// Message is currently playing audio
    /// </summary>
    Playing,
    
    /// <summary>
    /// Message playback is paused
    /// </summary>
    Paused,
    
    /// <summary>
    /// Message completed successfully
    /// </summary>
    Completed,
    
    /// <summary>
    /// Message was cancelled before completion
    /// </summary>
    Cancelled,
    
    /// <summary>
    /// Message failed due to an error
    /// </summary>
    Failed
}
